[package]
name = "lifetime_allocator"
version = "0.1.1"
edition = "2024"

[dependencies]
thiserror = { version = "2.0", default-features = false }
zerocopy = { version = "0.8", default-features = false, optional = true }

[features]
zerocopy = ["dep:zerocopy"]
